project:
  type: website

website:
  title: "Research Software Training @ EUR"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: "floating"
    contents:
      - text: "Home"
        href: home.qmd
      - section: Python Fundamentals
        href: python_fundamentals.qmd
        contents:
        - text: "Data (Collection) Types"
          href: Day1.ipynb
        - text: "Functions & Files"
          href: Day2.ipynb
        - text: "Pandas & Plots"
          href: Day3.ipynb
        - section: "Assignments"
          href: Instructions.ipynb
          contents:
          - text: "Assignments - Data (Collection) Types"
            href: Assignments_Day1.ipynb
          - text: "Assignments - Functions & Files"
            href: Assignments_Day2.ipynb
          - text: "Assignments - Pandas & Plots"
            href: Assignments_Day3.ipynb
      - section: Programming Caf√©
        contents:
        - text: "1 How to approach programming as a researcher (GitRepo)"
          href: https://codeberg.org/charliegreene/research-software-best-practice
        - text: "2 Automating Tasks with Python"
          href: lesson_2.md
        - text: "3 Basic command line usage in the Bash shell (PDF)"
          href: bash.qmd
        - text: "4 Clean your data with Python"
          href: DataCleaning.ipynb


format:
  html:
    theme: cosmo
    toc: true
    toc-location: right